<?php $presets["new1"] = array (
  'general-style' => 'minimalistic',
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#e8e8e8',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new1.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#2ed4b4',
  'general-border_radius' => 3,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'new1',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new1.header-logo-regular.png?w=120&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new1.header-logo-hd.png?w=240&h=160',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new1.bottom-bar-logo-regular.png?w=91&h=40',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new1.bottom-bar-logo-hd.png?w=182&h=80',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new1.general-floating-menu-logo-regular.png?w=91&h=40',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new1.general-floating-menu-logo-hd.png?w=182&h=80',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'sides',
  'top_bar-bg_color' => '#26282c',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#f4f5f8',
  'top_bar-dividers_color' => '#dadee1',
  'top_bar-dividers_opacity' => 100,
  'top_bar-dividers_ie_color' => '#dadee1',
  'top_bar-soc_icon_color' => '#f4f5f8',
  'top_bar-soc_icon_hover' => 'default',
  'top_bar-soc_icon_hover_color' => '#2ed4b4',
  'top_bar-soc_icon_show_round_outlines' => false,
  'header-bg_color' => '#ffffff',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#ffffff',
  'header-transparent_bg_opacity' => 90,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea_color' => '#373a41',
  'header-font_family' => 'Raleway:500',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_color' => '#474950',
  'header-hover' => 'default',
  'header-hover_color' => '#158cfb',
  'header-menu_bg_color' => '#6a6e71',
  'header-menu_bg_opacity' => 18,
  'header-menu_bg_ie_color' => '#dadee1',
  'header-hover_style' => 'underline',
  'header-hover_frame_border_radius' => 4,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 25,
  'header-submenu_color' => '#373a41',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => '#f7f7f8',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#373a41',
  'content-primary_text_color' => '#8d9095',
  'content-dividers_color' => '#e9ebec',
  'content-dividers_opacity' => 100,
  'content-dividers_ie_color' => '#e9ebec',
  'stripes-stripe_1_color' => '#26282c',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#f7f7f8',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#f4f5f8',
  'stripes-stripe_1_text_color' => '#8d9095',
  'stripes-stripe_1_div_color' => '#343538',
  'stripes-stripe_1_div_opacity' => 100,
  'stripes-stripe_1_div_ie_color' => '#343538',
  'stripes-stripe_2_color' => '#f6f6f6',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#f6f6f6',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#373a41',
  'stripes-stripe_2_text_color' => '#8d9095',
  'stripes-stripe_2_div_color' => '#e3e5e6',
  'stripes-stripe_2_div_opacity' => 100,
  'stripes-stripe_2_div_ie_color' => '#e1e3e4',
  'stripes-stripe_3_color' => '#f6f6f6',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new1.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#373a41',
  'stripes-stripe_3_text_color' => '#8d9095',
  'stripes-stripe_3_div_color' => '#e3e5e6',
  'stripes-stripe_3_div_opacity' => 100,
  'stripes-stripe_3_div_ie_color' => '#e3e5e6',
  'sidebar-bg_status' => 'disabled',
  'sidebar-bg_color' => '#ffffff',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#dadee1',
  'sidebar-dividers_opacity' => 80,
  'sidebar-dividers_ie_color' => '#dadee1',
  'sidebar-headers_color' => '#373a41',
  'sidebar-primary_text_color' => '#8d9095',
  'footer-bg_color' => '#26282c',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#343538',
  'footer-dividers_opacity' => 100,
  'footer-dividers_ie_color' => '#3f3f3f',
  'footer-headers_color' => '#f4f5f8',
  'footer-primary_text_color' => '#8d9095',
  'bottom_bar-bg_color' => '#303135',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#8d9095',
  'bottom_bar-dividers_color' => '#dadee1',
  'bottom_bar-dividers_opacity' => 100,
  'bottom_bar-dividers_ie_color' => '#dadee1',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Raleway:300',
  'fonts-h1_font_size' => 44,
  'fonts-h1_line_height' => 48,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Raleway',
  'fonts-h2_font_size' => 36,
  'fonts-h2_line_height' => 40,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Raleway:500',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 28,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Raleway:500',
  'fonts-h4_font_size' => 20,
  'fonts-h4_line_height' => 24,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Raleway:600',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Raleway:600',
  'fonts-h6_font_size' => 12,
  'fonts-h6_line_height' => 14,
  'fonts-h6_uppercase' => '1',
  'buttons-style' => 'flat',
  'buttons-s_font_family' => 'Raleway:500',
  'buttons-s_font_size' => 13,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 27,
  'buttons-s_border_radius' => 3,
  'buttons-m_font_family' => 'Raleway:500',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 36,
  'buttons-m_border_radius' => 3,
  'buttons-l_font_family' => 'Raleway:500',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 48,
  'buttons-l_border_radius' => 3,
  'hoover-style' => 'none',
  'hoover-color' => '#26282c',
  'hoover-opacity' => 60,
); ?>