<?php $presets["new2"] = array (
  'general-style' => 'minimalistic',
  'general-layout' => 'boxed',
  'general-boxed_bg_color' => '#f6f7f9',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new2.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#0fbcf5',
  'general-border_radius' => 2,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'new2',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new2.header-logo-regular.png?w=160&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new2.header-logo-hd.png?w=320&h=160',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new2.bottom-bar-logo-regular.png?w=112&h=41',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new2.bottom-bar-logo-hd.png?w=224&h=82',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new2.general-floating-menu-logo-regular.png?w=112&h=41',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new2.general-floating-menu-logo-hd.png?w=224&h=82',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'sides',
  'top_bar-bg_color' => '#ffffff',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#838992',
  'top_bar-dividers_color' => '#838992',
  'top_bar-dividers_opacity' => 100,
  'top_bar-dividers_ie_color' => '#dadbde',
  'top_bar-soc_icon_color' => '#838992',
  'top_bar-soc_icon_hover' => 'default',
  'top_bar-soc_icon_hover_color' => '#0a2731',
  'top_bar-soc_icon_show_round_outlines' => false,
  'header-bg_color' => '#1c2226',
  'header-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt05.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#000000',
  'header-transparent_bg_opacity' => 50,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Lato',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_color' => '#f3f6f7',
  'header-hover' => 'default',
  'header-hover_color' => '#2a83ed',
  'header-menu_bg_color' => '#838992',
  'header-menu_bg_opacity' => 30,
  'header-menu_bg_ie_color' => '#3a3f4a',
  'header-hover_style' => 'frame',
  'header-hover_frame_border_radius' => 2,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 6,
  'header-submenu_color' => '#373a41',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => 'f7f7f8',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#282e32',
  'content-primary_text_color' => '#838992',
  'content-dividers_color' => '#ebecee',
  'content-dividers_opacity' => 100,
  'content-dividers_ie_color' => '#ebecee',
  'stripes-stripe_1_color' => '#1c2226',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#151a1d',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt05.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#f3f6f7',
  'stripes-stripe_1_text_color' => '#838992',
  'stripes-stripe_1_div_color' => '#f3f6f7',
  'stripes-stripe_1_div_opacity' => 8,
  'stripes-stripe_1_div_ie_color' => '#353a3c',
  'stripes-stripe_2_color' => '#f6f6f6',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#f6f6f6',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#282e32',
  'stripes-stripe_2_text_color' => '#838992',
  'stripes-stripe_2_div_color' => '#e2e4e5',
  'stripes-stripe_2_div_opacity' => 100,
  'stripes-stripe_2_div_ie_color' => '#e2e4e5',
  'stripes-stripe_3_color' => '#f7f7f8',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new2.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#282e32',
  'stripes-stripe_3_text_color' => '#838992',
  'stripes-stripe_3_div_color' => '#282e32',
  'stripes-stripe_3_div_opacity' => 9,
  'stripes-stripe_3_div_ie_color' => '#dcddde',
  'sidebar-bg_status' => 'disabled',
  'sidebar-bg_color' => '#f6f6f6',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt05.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#ebecee',
  'sidebar-dividers_opacity' => 100,
  'sidebar-dividers_ie_color' => '#ebecee',
  'sidebar-headers_color' => '#373a41',
  'sidebar-primary_text_color' => '#838992',
  'footer-bg_color' => '#1c2226',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt05.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#f3f6f7',
  'footer-dividers_opacity' => 8,
  'footer-dividers_ie_color' => '#353a3c',
  'footer-headers_color' => '#f3f6f7',
  'footer-primary_text_color' => '#838992',
  'bottom_bar-bg_color' => '#ffffff',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new2.bottom-bar-bg-image.gif',
    'repeat' => 'repeat-x',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#838992',
  'bottom_bar-dividers_color' => '#838992',
  'bottom_bar-dividers_opacity' => 25,
  'bottom_bar-dividers_ie_color' => '#dadbde',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'PT Sans',
  'fonts-h1_font_size' => 46,
  'fonts-h1_line_height' => 50,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'PT Sans',
  'fonts-h2_font_size' => 34,
  'fonts-h2_line_height' => 38,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'PT Sans',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 28,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'PT Sans',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'PT Sans',
  'fonts-h5_font_size' => 18,
  'fonts-h5_line_height' => 24,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'PT Sans:700',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 16,
  'fonts-h6_uppercase' => false,
  'buttons-style' => 'flat',
  'buttons-s_font_family' => 'PT Sans',
  'buttons-s_font_size' => 14,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 29,
  'buttons-s_border_radius' => 3,
  'buttons-m_font_family' => 'PT Sans',
  'buttons-m_font_size' => 16,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 36,
  'buttons-m_border_radius' => 3,
  'buttons-l_font_family' => 'PT Sans',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 44,
  'buttons-l_border_radius' => 4,
  'hoover-style' => 'blur',
  'hoover-color' => '#090b0f',
  'hoover-opacity' => 45,
); ?>