<?php $presets["new3"] = array (
  'general-style' => 'minimalistic',
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#ebebeb',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new3.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#f7f7f7',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#7bcd40',
  'general-border_radius' => 1,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'new3',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new3.header-logo-regular.png?w=124&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new3.header-logo-hd.png?w=248&h=160',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new3.bottom-bar-logo-regular.png?w=94&h=28',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new3.bottom-bar-logo-hd.png?w=188&h=56',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new3.general-floating-menu-logo-regular.png?w=94&h=28',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new3.general-floating-menu-logo-hd.png?w=188&h=56',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'sides',
  'top_bar-bg_color' => '#7bcd40',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#ffffff',
  'top_bar-dividers_color' => '#ffffff',
  'top_bar-dividers_opacity' => 100,
  'top_bar-dividers_ie_color' => '#dadee1',
  'top_bar-soc_icon_color' => '#ffffff',
  'top_bar-soc_icon_hover' => 'custom',
  'top_bar-soc_icon_hover_color' => '#373a41',
  'top_bar-soc_icon_show_round_outlines' => false,
  'header-bg_color' => '#ffffff',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#ffffff',
  'header-transparent_bg_opacity' => 85,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 120,
  'header-layout' => 'classic',
  'header-contentarea_color' => '#373a41',
  'header-font_family' => 'Roboto Slab:700',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_color' => '#474950',
  'header-hover' => 'default',
  'header-hover_color' => '#2a83ed',
  'header-menu_bg_color' => '#373a41',
  'header-menu_bg_opacity' => 10,
  'header-menu_bg_ie_color' => '#dadee1',
  'header-hover_style' => 'frame',
  'header-hover_frame_border_radius' => 1,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 10,
  'header-submenu_color' => '#373a41',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => '#eeeeee',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#373a41',
  'content-primary_text_color' => '#8d9095',
  'content-dividers_color' => '#373a41',
  'content-dividers_opacity' => 10,
  'content-dividers_ie_color' => '#b6b6b6',
  'stripes-stripe_1_color' => '#373a41',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#ffffff',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#8d9095',
  'stripes-stripe_1_div_color' => '#474a51',
  'stripes-stripe_1_div_opacity' => 100,
  'stripes-stripe_1_div_ie_color' => '#474a51',
  'stripes-stripe_2_color' => '#eeeeee',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#f7f7f8',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#373a41',
  'stripes-stripe_2_text_color' => '#8d9095',
  'stripes-stripe_2_div_color' => '#373a41',
  'stripes-stripe_2_div_opacity' => 10,
  'stripes-stripe_2_div_ie_color' => '#eeeeee',
  'stripes-stripe_3_color' => '#ececec',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new3.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#373a41',
  'stripes-stripe_3_text_color' => '#8d9095',
  'stripes-stripe_3_div_color' => '#373a41',
  'stripes-stripe_3_div_opacity' => 12,
  'stripes-stripe_3_div_ie_color' => '#b6b6b6',
  'sidebar-bg_status' => 'partial_bg',
  'sidebar-bg_color' => '#ffffff',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#373a41',
  'sidebar-dividers_opacity' => 10,
  'sidebar-dividers_ie_color' => '#eeeeee',
  'sidebar-headers_color' => '#373a41',
  'sidebar-primary_text_color' => '#8d9095',
  'footer-bg_color' => '#ffffff',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#373a41',
  'footer-dividers_opacity' => 10,
  'footer-dividers_ie_color' => '#b6b6b6',
  'footer-headers_color' => '#373a41',
  'footer-primary_text_color' => '#8d9095',
  'bottom_bar-bg_color' => '#373a41',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#ffffff',
  'bottom_bar-dividers_color' => '#dadee1',
  'bottom_bar-dividers_opacity' => 85,
  'bottom_bar-dividers_ie_color' => '#dadee1',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Roboto Slab',
  'fonts-h1_font_size' => 42,
  'fonts-h1_line_height' => 46,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Roboto Slab',
  'fonts-h2_font_size' => 32,
  'fonts-h2_line_height' => 36,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Roboto Slab',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 26,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Roboto Slab:700',
  'fonts-h4_font_size' => 16,
  'fonts-h4_line_height' => 20,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Roboto Slab:700',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 23,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Roboto Slab:700',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 16,
  'fonts-h6_uppercase' => false,
  'buttons-style' => '3d',
  'buttons-s_font_family' => 'Roboto Slab',
  'buttons-s_font_size' => 13,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 28,
  'buttons-s_border_radius' => 4,
  'buttons-m_font_family' => 'Roboto Slab',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 34,
  'buttons-m_border_radius' => 4,
  'buttons-l_font_family' => 'Roboto Slab',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 44,
  'buttons-l_border_radius' => 4,
  'hoover-style' => 'blur',
  'hoover-color' => '#000000',
  'hoover-opacity' => 20,
); ?>