<?php $presets["new4"] = array (
  'general-style' => 'minimalistic',
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#f1afb0',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new4.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#815db2',
  'general-border_radius' => 2,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'new4',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new4.header-logo-regular.png?w=330&h=144',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new4.header-logo-hd.png?w=660&h=288',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new4.bottom-bar-logo-regular.png?w=36&h=36',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new4.bottom-bar-logo-hd.png?w=72&h=72',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/new4.general-floating-menu-logo-regular.png?w=36&h=50',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/new4.general-floating-menu-logo-hd.png?w=72&h=100',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'center',
  'top_bar-bg_color' => '#ffffff',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#8b8693',
  'top_bar-dividers_color' => '#838992',
  'top_bar-dividers_opacity' => 100,
  'top_bar-dividers_ie_color' => '#dadbde',
  'top_bar-soc_icon_color' => '#8b8693',
  'top_bar-soc_icon_hover' => 'default',
  'top_bar-soc_icon_hover_color' => '#3e2a50',
  'top_bar-soc_icon_show_round_outlines' => false,
  'header-bg_color' => '#170c26',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#0b0316',
  'header-transparent_bg_opacity' => 65,
  'header-transparent_bg_ie_color' => '#170c26',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 180,
  'header-layout' => 'center',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Signika',
  'header-font_size' => 17,
  'header-font_uppercase' => '1',
  'header-font_color' => '#ffffff',
  'header-hover' => 'default',
  'header-hover_color' => '#2a83ed',
  'header-menu_bg_color' => '#838992',
  'header-menu_bg_opacity' => 30,
  'header-menu_bg_ie_color' => '#3a3f4a',
  'header-hover_style' => 'none',
  'header-hover_frame_border_radius' => 2,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 27,
  'header-submenu_color' => '#373a41',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => 'f7f7f8',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#141119',
  'content-primary_text_color' => '#817f86',
  'content-dividers_color' => '#170c26',
  'content-dividers_opacity' => 8,
  'content-dividers_ie_color' => '#ebecee',
  'stripes-stripe_1_color' => '#170c26',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#151a1d',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#9c92a6',
  'stripes-stripe_1_div_color' => '#ffffff',
  'stripes-stripe_1_div_opacity' => 11,
  'stripes-stripe_1_div_ie_color' => '#393539',
  'stripes-stripe_2_color' => '#f3f2f3',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#f3f2f3',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#141119',
  'stripes-stripe_2_text_color' => '#817f86',
  'stripes-stripe_2_div_color' => '#170c26',
  'stripes-stripe_2_div_opacity' => 8,
  'stripes-stripe_2_div_ie_color' => '#e2e4e5',
  'stripes-stripe_3_color' => '#f7f7f8',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new4.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#141119',
  'stripes-stripe_3_text_color' => '#817f86',
  'stripes-stripe_3_div_color' => '#170c26',
  'stripes-stripe_3_div_opacity' => 8,
  'stripes-stripe_3_div_ie_color' => '#dcddde',
  'sidebar-bg_status' => 'disabled',
  'sidebar-bg_color' => '#f6f6f6',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt05.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#ebecee',
  'sidebar-dividers_opacity' => 100,
  'sidebar-dividers_ie_color' => '#ebecee',
  'sidebar-headers_color' => '#141119',
  'sidebar-primary_text_color' => '#817f86',
  'footer-bg_color' => '#170c26',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#170c26',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#ffffff',
  'footer-dividers_opacity' => 11,
  'footer-dividers_ie_color' => '#393539',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#9c92a6',
  'bottom_bar-bg_color' => '#ffffff',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/new4.bottom-bar-bg-image.jpg',
    'repeat' => 'repeat-x',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#8b8693',
  'bottom_bar-dividers_color' => '#838992',
  'bottom_bar-dividers_opacity' => 25,
  'bottom_bar-dividers_ie_color' => '#dadbde',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Signika:600',
  'fonts-h1_font_size' => 46,
  'fonts-h1_line_height' => 50,
  'fonts-h1_uppercase' => '1',
  'fonts-h2_font_family' => 'Signika:600',
  'fonts-h2_font_size' => 34,
  'fonts-h2_line_height' => 38,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Signika:600',
  'fonts-h3_font_size' => 22,
  'fonts-h3_line_height' => 26,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Signika:600',
  'fonts-h4_font_size' => 20,
  'fonts-h4_line_height' => 24,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Signika:600',
  'fonts-h5_font_size' => 18,
  'fonts-h5_line_height' => 24,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Signika:600',
  'fonts-h6_font_size' => 16,
  'fonts-h6_line_height' => 18,
  'fonts-h6_uppercase' => false,
  'buttons-style' => 'flat',
  'buttons-s_font_family' => 'Signika',
  'buttons-s_font_size' => 14,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 31,
  'buttons-s_border_radius' => 3,
  'buttons-m_font_family' => 'Signika',
  'buttons-m_font_size' => 16,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 38,
  'buttons-m_border_radius' => 3,
  'buttons-l_font_family' => 'Signika',
  'buttons-l_font_size' => 20,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 48,
  'buttons-l_border_radius' => 4,
  'hoover-style' => 'none',
  'hoover-color' => '#815db2',
  'hoover-opacity' => 75,
); ?>