<?php $presets["new6"] = array (
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin1.header-logo-regular.png?w=49&h=78',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin1.header-logo-hd.png?w=98&h=156',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin1.bottom-bar-logo-regular.png?w=27&h=53',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin1.bottom-bar-logo-hd.png?w=54&h=106',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin1.general-floating-menu-logo-regular.png?w=27&h=53',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin1.general-floating-menu-logo-hd.png?w=54&h=106',
    1 => 0,
  ),
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#94c2e3',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin1.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-show_titles' => '1',
  'general-show_breadcrumbs' => '1',
  'general-responsive' => '1',
  'general-accent_bg_color' => '#3b8ced',
  'general-border_radius' => 4,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Open Sans:300',
  'fonts-h1_font_size' => 48,
  'fonts-h1_line_height' => 52,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Open Sans:300',
  'fonts-h2_font_size' => 36,
  'fonts-h2_line_height' => 40,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Open Sans',
  'fonts-h3_font_size' => 22,
  'fonts-h3_line_height' => 26,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Open Sans',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Open Sans',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Open Sans:600',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 16,
  'fonts-h6_uppercase' => false,
  'buttons-s_font_family' => 'Open Sans',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 27,
  'buttons-m_font_family' => 'Open Sans',
  'buttons-m_font_size' => 13,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 32,
  'buttons-l_font_family' => 'Open Sans',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 43,
  'top_bar-bg_color' => '#3b8ced',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#3b8ced',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#ffffff',
  'top_bar-dividers_color' => '#ffffff',
  'top_bar-dividers_opacity' => 100,
  'top_bar-dividers_ie_color' => '#dadee1',
  'top_bar-soc_icon_color' => '#ffffff',
  'top_bar-soc_icon_hover' => 'custom',
  'top_bar-soc_icon_hover_color' => '#a5ccfb',
  'header-bg_color' => '#ffffff',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#ffffff',
  'header-transparent_bg_opacity' => 70,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 110,
  'header-layout' => 'left',
  'header-contentarea_color' => '#373a41',
  'header-font_family' => 'Open Sans',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_color' => '#474950',
  'header-menu_bg_color' => '#6a6e71',
  'header-menu_bg_opacity' => 18,
  'header-menu_bg_ie_color' => '#dadee1',
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'header-submenu_color' => '#373a41',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => '#f7f7f8',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#373a41',
  'content-primary_text_color' => '#8d9095',
  'content-dividers_color' => '#dadee1',
  'content-dividers_opacity' => 70,
  'content-dividers_ie_color' => '#dadee1',
  'stripes-stripe_1_color' => '#202124',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#202124',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#a1a5ad',
  'stripes-stripe_1_div_color' => '#a1a5ad',
  'stripes-stripe_1_div_opacity' => 14,
  'stripes-stripe_1_div_ie_color' => '#323337',
  'stripes-stripe_2_color' => '#373a41',
  'stripes-stripe_2_opacity' => 4,
  'stripes-stripe_2_ie_color' => '#f7f7f8',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#373a41',
  'stripes-stripe_2_text_color' => '#8d9095',
  'stripes-stripe_2_div_color' => '#dadee1',
  'stripes-stripe_2_div_opacity' => 77,
  'stripes-stripe_2_div_ie_color' => '#dadee1',
  'stripes-stripe_3_color' => '#d1edfa',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin1.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#292941',
  'stripes-stripe_3_text_color' => '#6e7a91',
  'stripes-stripe_3_div_color' => '#292941',
  'stripes-stripe_3_div_opacity' => 12,
  'stripes-stripe_3_div_ie_color' => '#afc5d2',
  'sidebar-bg_color' => '#ffffff',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#dadee1',
  'sidebar-dividers_opacity' => 70,
  'sidebar-dividers_ie_color' => '#dadee1',
  'sidebar-headers_color' => '#373a41',
  'sidebar-primary_text_color' => '#8d9095',
  'footer-bg_color' => '#f7f7f8',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#dadee1',
  'footer-dividers_opacity' => 75,
  'footer-dividers_ie_color' => '#dadee1',
  'footer-headers_color' => '#373a41',
  'footer-primary_text_color' => '#8d9095',
  'bottom_bar-bg_color' => '#f0f0f1',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#8d9095',
  'bottom_bar-dividers_color' => '#474950',
  'bottom_bar-dividers_opacity' => 12,
  'bottom_bar-dividers_ie_color' => '#dadee1',
  'hoover-color' => '#000000',
  'hoover-opacity' => 30,
  'hoover-style' => 'blur',
  'header-hover' => 'default',
  'header-hover_color' => '#5bcbff',
  'header-hover_style' => 'underline',
  'general-style' => 'minimalistic',
  'sidebar-bg_status' => 'disabled',
  'buttons-style' => 'flat',
  'buttons-s_border_radius' => 4,
  'buttons-m_border_radius' => 4,
  'buttons-l_border_radius' => 5,
  'top_bar-soc_icon_show_round_outlines' => false,
  'menu-items_distance' => 25,
  'header-hover_frame_border_radius' => 4,
  'top_bar-content_alignment' => 'sides',
  'preset' => 'new6',
); ?>