<?php $presets["skin4"] = array (
  'general-style' => 'minimalistic',
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#b6b3ab',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin4.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#f9f6ef',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin4.general-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#dc334b',
  'general-border_radius' => 4,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'skin4',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin4.header-logo-regular.png?w=115&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin4.header-logo-hd.png?w=230&h=160',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin4.bottom-bar-logo-regular.png?w=94&h=27',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin4.bottom-bar-logo-hd.png?w=188&h=54',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin4.general-floating-menu-logo-regular.png?w=94&h=27',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin4.general-floating-menu-logo-hd.png?w=188&h=54',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'sides',
  'top_bar-bg_color' => '#242b32',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin4.top-bar-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#777f88',
  'top_bar-dividers_color' => '#777f88',
  'top_bar-dividers_opacity' => 30,
  'top_bar-dividers_ie_color' => '#3c4653',
  'top_bar-soc_icon_color' => '#636c78',
  'top_bar-soc_icon_hover' => 'custom',
  'top_bar-soc_icon_hover_color' => '#ffffff',
  'top_bar-soc_icon_show_round_outlines' => '1',
  'header-bg_color' => '#131b22',
  'header-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin4.header-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#080c10',
  'header-transparent_bg_opacity' => 50,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Roboto Slab',
  'header-font_size' => 15,
  'header-font_uppercase' => '1',
  'header-font_color' => '#ffffff',
  'header-hover' => 'default',
  'header-hover_color' => '#158cfb',
  'header-menu_bg_color' => '#777f88',
  'header-menu_bg_opacity' => 30,
  'header-menu_bg_ie_color' => '#3c4653',
  'header-hover_style' => 'none',
  'header-hover_frame_border_radius' => 4,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 25,
  'header-submenu_color' => '#4f5359',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => '#1c1a18',
  'slideshow-bg_opacity' => 4,
  'slideshow-bg_ie_color' => '#f7f7f8',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#1c1a18',
  'content-primary_text_color' => '#979590',
  'content-dividers_color' => '#1c1a18',
  'content-dividers_opacity' => 10,
  'content-dividers_ie_color' => '#dcd9d3',
  'stripes-stripe_1_color' => '#131b22',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#f7f7f8',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin4.stripes-stripe-1-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#777f88',
  'stripes-stripe_1_div_color' => '#777f88',
  'stripes-stripe_1_div_opacity' => 20,
  'stripes-stripe_1_div_ie_color' => '#38414d',
  'stripes-stripe_2_color' => '#1c1a18',
  'stripes-stripe_2_opacity' => 4,
  'stripes-stripe_2_ie_color' => '#eae9e5',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#1c1a18',
  'stripes-stripe_2_text_color' => '#8b8a88',
  'stripes-stripe_2_div_color' => '#1c1a18',
  'stripes-stripe_2_div_opacity' => 10,
  'stripes-stripe_2_div_ie_color' => '#dcd9d3',
  'stripes-stripe_3_color' => '#dbd8d0',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin4.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#1c1a18',
  'stripes-stripe_3_text_color' => '#7b7a79',
  'stripes-stripe_3_div_color' => '#1c1a18',
  'stripes-stripe_3_div_opacity' => 10,
  'stripes-stripe_3_div_ie_color' => '#dcd9d3',
  'sidebar-bg_status' => 'partial_bg',
  'sidebar-bg_color' => '#1c1a18',
  'sidebar-bg_opacity' => 4,
  'sidebar-bg_ie_color' => '#eae9e5',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#1c1a18',
  'sidebar-dividers_opacity' => 10,
  'sidebar-dividers_ie_color' => '#dcd9d3',
  'sidebar-headers_color' => '#1c1a18',
  'sidebar-primary_text_color' => '#8b8a88',
  'footer-bg_color' => '#131b22',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin4.footer-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#777f88',
  'footer-dividers_opacity' => 20,
  'footer-dividers_ie_color' => '#38414d',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#777f88',
  'bottom_bar-bg_color' => '#242b32',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin4.bottom-bar-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#777f88',
  'bottom_bar-dividers_color' => '#777f88',
  'bottom_bar-dividers_opacity' => 30,
  'bottom_bar-dividers_ie_color' => '#38414d',
  'fonts-font_family' => 'Tahoma',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 16,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Roboto Slab',
  'fonts-h1_font_size' => 40,
  'fonts-h1_line_height' => 44,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Roboto Slab',
  'fonts-h2_font_size' => 34,
  'fonts-h2_line_height' => 38,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Roboto Slab',
  'fonts-h3_font_size' => 26,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Roboto Slab',
  'fonts-h4_font_size' => 20,
  'fonts-h4_line_height' => 24,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Roboto Slab',
  'fonts-h5_font_size' => 18,
  'fonts-h5_line_height' => 24,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Roboto Slab:700',
  'fonts-h6_font_size' => 16,
  'fonts-h6_line_height' => 18,
  'fonts-h6_uppercase' => '1',
  'buttons-style' => '3d',
  'buttons-s_font_family' => 'Roboto Slab',
  'buttons-s_font_size' => 13,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 28,
  'buttons-s_border_radius' => 4,
  'buttons-m_font_family' => 'Roboto Slab',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 34,
  'buttons-m_border_radius' => 5,
  'buttons-l_font_family' => 'Roboto Slab',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 43,
  'buttons-l_border_radius' => 6,
  'hoover-style' => 'blur',
  'hoover-color' => '#131b22',
  'hoover-opacity' => 61,
); ?>