<?php $presets["skin3"] = array (
  'general-style' => 'ios7',
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#1b3a60',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin3.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#09111b',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#1585d4',
  'general-border_radius' => 2,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'skin3',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin3.header-logo-regular.png?w=46&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin3.header-logo-hd.png?w=92&h=160',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin3.bottom-bar-logo-regular.png?w=28&h=50',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin3.bottom-bar-logo-hd.png?w=56&h=100',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin3.general-floating-menu-logo-regular.png?w=28&h=50',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin3.general-floating-menu-logo-hd.png?w=56&h=100',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'sides',
  'top_bar-bg_color' => '#09111b',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#6d7c8d',
  'top_bar-dividers_color' => '#1d2935',
  'top_bar-dividers_opacity' => 100,
  'top_bar-dividers_ie_color' => '#18232e',
  'top_bar-soc_icon_color' => '#0d598f',
  'top_bar-soc_icon_hover' => 'custom',
  'top_bar-soc_icon_hover_color' => '#178fe3',
  'top_bar-soc_icon_show_round_outlines' => '1',
  'header-bg_color' => '#09111b',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#09111b',
  'header-transparent_bg_opacity' => 40,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 110,
  'header-layout' => 'left',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Open Sans',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_color' => '#ffffff',
  'header-hover' => 'default',
  'header-hover_color' => '#158cfb',
  'header-menu_bg_color' => '#6d7d8d',
  'header-menu_bg_opacity' => 21,
  'header-menu_bg_ie_color' => '#2b333e',
  'header-hover_style' => 'frame',
  'header-hover_frame_border_radius' => 2,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 5,
  'header-submenu_color' => '#1b2838',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => '#ffffff',
  'slideshow-bg_opacity' => 4,
  'slideshow-bg_ie_color' => '#1e2530',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#ffffff',
  'content-primary_text_color' => '#6d7c8d',
  'content-dividers_color' => '#1d2935',
  'content-dividers_opacity' => 100,
  'content-dividers_ie_color' => '#1d2935',
  'stripes-stripe_1_color' => '#121a23',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#121a23',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#6d7c8d',
  'stripes-stripe_1_div_color' => '#1d2935',
  'stripes-stripe_1_div_opacity' => 100,
  'stripes-stripe_1_div_ie_color' => '#1d2935',
  'stripes-stripe_2_color' => '#121a23',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#121a23',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_text_color' => '#6d7c8d',
  'stripes-stripe_2_div_color' => '#1d2935',
  'stripes-stripe_2_div_opacity' => 100,
  'stripes-stripe_2_div_ie_color' => '#1d2935',
  'stripes-stripe_3_color' => '#102641',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin3.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#ffffff',
  'stripes-stripe_3_text_color' => '#f4f8fb',
  'stripes-stripe_3_div_color' => '#ffffff',
  'stripes-stripe_3_div_opacity' => 12,
  'stripes-stripe_3_div_ie_color' => '#283b53',
  'sidebar-bg_status' => 'all_bg',
  'sidebar-bg_color' => '#121a23',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#f9fafa',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#1d2935',
  'sidebar-dividers_opacity' => 100,
  'sidebar-dividers_ie_color' => '#1d2935',
  'sidebar-headers_color' => '#ffffff',
  'sidebar-primary_text_color' => '#8693a0',
  'footer-bg_color' => '#121a23',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#1d2935',
  'footer-dividers_opacity' => 100,
  'footer-dividers_ie_color' => '#1d2935',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#6d7c8d',
  'bottom_bar-bg_color' => '#09111b',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#6d7c8d',
  'bottom_bar-dividers_color' => '#1d2935',
  'bottom_bar-dividers_opacity' => 100,
  'bottom_bar-dividers_ie_color' => '#1d2935',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Open Sans:300',
  'fonts-h1_font_size' => 48,
  'fonts-h1_line_height' => 52,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Open Sans:300',
  'fonts-h2_font_size' => 34,
  'fonts-h2_line_height' => 38,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Open Sans',
  'fonts-h3_font_size' => 22,
  'fonts-h3_line_height' => 26,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Open Sans',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Open Sans',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Open Sans',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 16,
  'fonts-h6_uppercase' => false,
  'buttons-style' => 'flat',
  'buttons-s_font_family' => 'Open Sans',
  'buttons-s_font_size' => 14,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 31,
  'buttons-s_border_radius' => 2,
  'buttons-m_font_family' => 'Open Sans',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 38,
  'buttons-m_border_radius' => 2,
  'buttons-l_font_family' => 'Open Sans',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 48,
  'buttons-l_border_radius' => 3,
  'hoover-style' => 'none',
  'hoover-color' => '#1585d4',
  'hoover-opacity' => 75,
); ?>