<?php $presets["skin2"] = array (
  'general-style' => 'ios7',
  'general-layout' => 'boxed',
  'general-boxed_bg_color' => '#eaeaea',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin2.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#5fd45c',
  'general-border_radius' => 4,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'skin2',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin2.header-logo-regular.png?w=114&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin2.header-logo-hd.png?w=228&h=160',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin2.bottom-bar-logo-regular.png?w=77&h=25',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin2.bottom-bar-logo-hd.png?w=154&h=50',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin2.general-floating-menu-logo-regular.png?w=77&h=25',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin2.general-floating-menu-logo-hd.png?w=154&h=50',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'sides',
  'top_bar-bg_color' => '#006fa8',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#ffffff',
  'top_bar-dividers_color' => '#2287bb',
  'top_bar-dividers_opacity' => 100,
  'top_bar-dividers_ie_color' => '#1f81b3',
  'top_bar-soc_icon_color' => '#ffffff',
  'top_bar-soc_icon_hover' => 'custom',
  'top_bar-soc_icon_hover_color' => '#5bcbff',
  'top_bar-soc_icon_show_round_outlines' => false,
  'header-bg_color' => '#006fa8',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#002233',
  'header-transparent_bg_opacity' => 30,
  'header-transparent_bg_ie_color' => '#006fa8',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Open Sans',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_color' => '#ffffff',
  'header-hover' => 'custom',
  'header-hover_color' => '#5bcbff',
  'header-menu_bg_color' => '#6f7b8b',
  'header-menu_bg_opacity' => 21,
  'header-menu_bg_ie_color' => '#293442',
  'header-hover_style' => 'frame',
  'header-hover_frame_border_radius' => 4,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 5,
  'header-submenu_color' => '#1b2838',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => '#f6f7f7',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#1b2838',
  'content-primary_text_color' => '#8f969f',
  'content-dividers_color' => '#6f7b8b',
  'content-dividers_opacity' => 14,
  'content-dividers_ie_color' => '#dadee1',
  'stripes-stripe_1_color' => '#006fa8',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#f7f7f8',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#ffffff',
  'stripes-stripe_1_div_color' => '#2287bb',
  'stripes-stripe_1_div_opacity' => 100,
  'stripes-stripe_1_div_ie_color' => '#1f81b3',
  'stripes-stripe_2_color' => '#f6f7f7',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => 'f6f7f7',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#1b2838',
  'stripes-stripe_2_text_color' => '#8f969f',
  'stripes-stripe_2_div_color' => '#6f7b8b',
  'stripes-stripe_2_div_opacity' => 14,
  'stripes-stripe_2_div_ie_color' => '#dadee1',
  'stripes-stripe_3_color' => '#f7f8f8',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin2.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#1b2838',
  'stripes-stripe_3_text_color' => '#8f969f',
  'stripes-stripe_3_div_color' => '#6f7b8b',
  'stripes-stripe_3_div_opacity' => 14,
  'stripes-stripe_3_div_ie_color' => '#ffffff',
  'sidebar-bg_status' => 'all_bg',
  'sidebar-bg_color' => '#f9fafa',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#f9fafa',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#6f7b8b',
  'sidebar-dividers_opacity' => 15,
  'sidebar-dividers_ie_color' => '#dadee1',
  'sidebar-headers_color' => '#1b2838',
  'sidebar-primary_text_color' => '#8f969f',
  'footer-bg_color' => '#006fa8',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#2287bb',
  'footer-dividers_opacity' => 100,
  'footer-dividers_ie_color' => '#1f81b3',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#ffffff',
  'bottom_bar-bg_color' => '#006fa8',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#ffffff',
  'bottom_bar-dividers_color' => '#2287bb',
  'bottom_bar-dividers_opacity' => 100,
  'bottom_bar-dividers_ie_color' => '#1f81b3',
  'fonts-font_family' => 'Open Sans',
  'fonts-normal_size' => 13,
  'fonts-small_size' => 11,
  'fonts-big_size' => 14,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Open Sans:300',
  'fonts-h1_font_size' => 46,
  'fonts-h1_line_height' => 50,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Open Sans:300',
  'fonts-h2_font_size' => 34,
  'fonts-h2_line_height' => 38,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Open Sans',
  'fonts-h3_font_size' => 22,
  'fonts-h3_line_height' => 26,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Open Sans',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Open Sans',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Open Sans',
  'fonts-h6_font_size' => 13,
  'fonts-h6_line_height' => 15,
  'fonts-h6_uppercase' => false,
  'buttons-style' => 'flat',
  'buttons-s_font_family' => 'Open Sans',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 27,
  'buttons-s_border_radius' => 4,
  'buttons-m_font_family' => 'Open Sans',
  'buttons-m_font_size' => 14,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 35,
  'buttons-m_border_radius' => 4,
  'buttons-l_font_family' => 'Open Sans',
  'buttons-l_font_size' => 16,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 45,
  'buttons-l_border_radius' => 5,
  'hoover-style' => 'none',
  'hoover-color' => '#5fd45c',
  'hoover-opacity' => 75,
); ?>