<?php $presets["skin5"] = array (
  'general-style' => 'minimalistic',
  'general-layout' => 'boxed',
  'general-boxed_bg_color' => '#ce4747',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin5.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#e75050',
  'general-border_radius' => 5,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'skin5',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin5.header-logo-regular.png?w=124&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin5.header-logo-hd.png?w=248&h=160',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin5.bottom-bar-logo-regular.png?w=87&h=33',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin5.bottom-bar-logo-hd.png?w=174&h=66',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin5.general-floating-menu-logo-regular.png?w=49&h=50',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin5.general-floating-menu-logo-hd.png?w=98&h=100',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'sides',
  'top_bar-bg_color' => '#222428',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#797a7f',
  'top_bar-dividers_color' => '#ffffff',
  'top_bar-dividers_opacity' => 25,
  'top_bar-dividers_ie_color' => '#dadbde',
  'top_bar-soc_icon_color' => '#e75050',
  'top_bar-soc_icon_hover' => 'custom',
  'top_bar-soc_icon_hover_color' => '#ffffff',
  'top_bar-soc_icon_show_round_outlines' => false,
  'header-bg_color' => '#121418',
  'header-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin5.header-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#121418',
  'header-transparent_bg_opacity' => 60,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Droid Sans',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_color' => '#ffffff',
  'header-hover' => 'custom',
  'header-hover_color' => '#e75050',
  'header-menu_bg_color' => '#838992',
  'header-menu_bg_opacity' => 30,
  'header-menu_bg_ie_color' => '#3a3f4a',
  'header-hover_style' => 'underline',
  'header-hover_frame_border_radius' => 5,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 25,
  'header-submenu_color' => '#373a41',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => 'f7f7f8',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#373a41',
  'content-primary_text_color' => '#838992',
  'content-dividers_color' => '#373a41',
  'content-dividers_opacity' => 11,
  'content-dividers_ie_color' => '#edeeef',
  'stripes-stripe_1_color' => '#121418',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#f7f7f8',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin5.stripes-stripe-1-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#797a7f',
  'stripes-stripe_1_div_color' => '#2d3034',
  'stripes-stripe_1_div_opacity' => 100,
  'stripes-stripe_1_div_ie_color' => '#2d3034',
  'stripes-stripe_2_color' => '#f6f6f6',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#f7f7f8',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#373a41',
  'stripes-stripe_2_text_color' => '#838992',
  'stripes-stripe_2_div_color' => '#373a41',
  'stripes-stripe_2_div_opacity' => 11,
  'stripes-stripe_2_div_ie_color' => '#e5e6e8',
  'stripes-stripe_3_color' => '#4c2021',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#36191a',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin5.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#ffffff',
  'stripes-stripe_3_text_color' => '#ffffff',
  'stripes-stripe_3_div_color' => '#9f7171',
  'stripes-stripe_3_div_opacity' => 16,
  'stripes-stripe_3_div_ie_color' => '#593d3e',
  'sidebar-bg_status' => 'disabled',
  'sidebar-bg_color' => '#ffffff',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#373a41',
  'sidebar-dividers_opacity' => 11,
  'sidebar-dividers_ie_color' => '#edeeef',
  'sidebar-headers_color' => '#373a41',
  'sidebar-primary_text_color' => '#838992',
  'footer-bg_color' => '#121418',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin5.footer-bg-image.gif',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#2d3034',
  'footer-dividers_opacity' => 100,
  'footer-dividers_ie_color' => '#3a3f4a',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#797a7f',
  'bottom_bar-bg_color' => '#222428',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#797a7f',
  'bottom_bar-dividers_color' => '#838992',
  'bottom_bar-dividers_opacity' => 25,
  'bottom_bar-dividers_ie_color' => '#dadbde',
  'fonts-font_family' => 'Droid Sans',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 16,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Droid Sans',
  'fonts-h1_font_size' => 40,
  'fonts-h1_line_height' => 44,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Droid Sans',
  'fonts-h2_font_size' => 30,
  'fonts-h2_line_height' => 34,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Droid Sans',
  'fonts-h3_font_size' => 22,
  'fonts-h3_line_height' => 26,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Droid Sans',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Droid Sans',
  'fonts-h5_font_size' => 18,
  'fonts-h5_line_height' => 24,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Droid Sans',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 16,
  'fonts-h6_uppercase' => false,
  'buttons-style' => 'flat',
  'buttons-s_font_family' => 'Open Sans',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 27,
  'buttons-s_border_radius' => 3,
  'buttons-m_font_family' => 'Open Sans',
  'buttons-m_font_size' => 13,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 30,
  'buttons-m_border_radius' => 3,
  'buttons-l_font_family' => 'Open Sans',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 39,
  'buttons-l_border_radius' => 3,
  'hoover-style' => 'blur',
  'hoover-color' => '#e75050',
  'hoover-opacity' => 75,
); ?>