<?php $presets["skin6"] = array (
  'general-style' => 'minimalistic',
  'general-layout' => 'boxed',
  'general-boxed_bg_color' => '#88a9be',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin6.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-accent_bg_color' => '#589eca',
  'general-border_radius' => 3,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-responsive' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'preset' => 'skin6',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin6.header-logo-regular.png?w=121&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin6.header-logo-hd.png?w=242&h=160',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin6.bottom-bar-logo-regular.png?w=33&h=34',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin6.bottom-bar-logo-hd.png?w=66&h=68',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin6.general-floating-menu-logo-regular.png?w=82&h=35',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin6.general-floating-menu-logo-hd.png?w=164&h=70',
    1 => 0,
  ),
  'top_bar-content_alignment' => 'sides',
  'top_bar-bg_color' => '#ffffff',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#2f2926',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#868685',
  'top_bar-dividers_color' => '#847f7b',
  'top_bar-dividers_opacity' => 30,
  'top_bar-dividers_ie_color' => '#433a34',
  'top_bar-soc_icon_color' => '#589eca',
  'top_bar-soc_icon_hover' => 'custom',
  'top_bar-soc_icon_hover_color' => '#357ba7',
  'top_bar-soc_icon_show_round_outlines' => false,
  'header-bg_color' => '#231d1a',
  'header-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt09.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#231d1a',
  'header-transparent_bg_opacity' => 75,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt09.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 130,
  'header-layout' => 'classic',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Open Sans',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_color' => '#ffffff',
  'header-hover' => 'default',
  'header-hover_color' => '#2a83ed',
  'header-menu_bg_color' => '#807870',
  'header-menu_bg_opacity' => 30,
  'header-menu_bg_ie_color' => '#433a34',
  'header-hover_style' => 'frame',
  'header-hover_frame_border_radius' => 3,
  'header-next_level_indicator' => false,
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 10,
  'header-submenu_color' => '#ffffff',
  'header-submenu_bg_color' => '#292421',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#292421',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'slideshow-bg_color' => '#f5f5f4',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#f5f5f4',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#2b271e',
  'content-primary_text_color' => '#8e9294',
  'content-dividers_color' => '#8b8a88',
  'content-dividers_opacity' => 16,
  'content-dividers_ie_color' => '#ededec',
  'stripes-stripe_1_color' => '#231d1a',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#f7f7f8',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt09.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#847f7b',
  'stripes-stripe_1_div_color' => '#352e2b',
  'stripes-stripe_1_div_opacity' => 100,
  'stripes-stripe_1_div_ie_color' => '#2f2926',
  'stripes-stripe_2_color' => '#231d1a',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#f8f7f9',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt09.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_text_color' => '#847f7b',
  'stripes-stripe_2_div_color' => '#352e2b',
  'stripes-stripe_2_div_opacity' => 100,
  'stripes-stripe_2_div_ie_color' => '#2f2926',
  'stripes-stripe_3_color' => '#edeeef',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#edeeef',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin6.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#2b271e',
  'stripes-stripe_3_text_color' => '#8e9294',
  'stripes-stripe_3_div_color' => '#767470',
  'stripes-stripe_3_div_opacity' => 16,
  'stripes-stripe_3_div_ie_color' => '#c7c6c6',
  'sidebar-bg_status' => 'partial_bg',
  'sidebar-bg_color' => '#231d1a',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt09.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#352e2b',
  'sidebar-dividers_opacity' => 100,
  'sidebar-dividers_ie_color' => '#352e2b',
  'sidebar-headers_color' => '#ffffff',
  'sidebar-primary_text_color' => '#847f7b',
  'footer-bg_color' => '#231d1a',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt09.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#352e2b',
  'footer-dividers_opacity' => 100,
  'footer-dividers_ie_color' => '#352e2b',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#847f7b',
  'bottom_bar-bg_color' => '#2f2926',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#2f2926',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#847f7b',
  'bottom_bar-dividers_color' => '#2f2926',
  'bottom_bar-dividers_opacity' => 100,
  'bottom_bar-dividers_ie_color' => '#2f2926',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Open Sans:300',
  'fonts-h1_font_size' => 50,
  'fonts-h1_line_height' => 54,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Open Sans:300',
  'fonts-h2_font_size' => 40,
  'fonts-h2_line_height' => 44,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Open Sans',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 28,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Open Sans',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Open Sans',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 24,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Open Sans:600',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 18,
  'fonts-h6_uppercase' => false,
  'buttons-style' => 'flat',
  'buttons-s_font_family' => 'Open Sans',
  'buttons-s_font_size' => 13,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 30,
  'buttons-s_border_radius' => 3,
  'buttons-m_font_family' => 'Open Sans',
  'buttons-m_font_size' => 16,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 40,
  'buttons-m_border_radius' => 3,
  'buttons-l_font_family' => 'Open Sans',
  'buttons-l_font_size' => 20,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 48,
  'buttons-l_border_radius' => 3,
  'hoover-style' => 'blur',
  'hoover-color' => '#2b271e',
  'hoover-opacity' => 50,
); ?>